local icons = {
kind = {
   Text = "",
   -- Method = "m",
   Function = "",
   -- Constructor = "",
   Method = " ",
   -- Function = "",
   Constructor = "",
   Field = "",
   -- Variable = "",
   Variable = "",
   Class = "",
   Interface = "",
   -- Module = "",
   Module = "",
   Property = "",
   Unit = "",
   Value = "",
   Enum = "",
   -- Keyword = "",
   Keyword = "",
   Snippet = "",
   -- Snippet = "",
   Color = "",
   File = "",
   Reference = "",
   Folder = "",
   EnumMember = "",
   Constant = "",
   Struct = "",
   Event = "",
   Operator = "",
   TypeParameter = "",
   Namespace = "蘒",
 },
 type = {
   Array = "",
   Number = " ",
   String = "",
   Boolean = "蘒",
   Object = "",
   Key = " ",
   Null = "Null",
 },
 documents = {
   -- File = "",
   Files = "",
   -- Folder = "",
   OpenFolder = "",
 },
 git = {
   Add = "",
   Mod = "",
   Remove = "",
   Ignore = "",
   Rename = "",
   Diff = "",
   Repo = "",
 },
 ui = {
   Lock = "",
   Circle = "",
   BigCircle = "",
   BigUnfilledCircle = "",
   Close = "",
   NewFile = "",
   Search = "",
   Lightbulb = "",
   Project = "",
   Dashboard = "",
   History = "",
   Comment = "",
   Bug = "",
   Code = "",
   Telescope = "",
   Gear = "",
   Package = "",
   List = "",
   SignIn = "",
   Check = "",
   Fire = " ",
   Note = "",
   BookMark = "",
   Pencil = "",
   -- ChevronRight = "",
   ChevronRight = ">",
   Table = "",
   Calendar = "",
 },
 diagnostics = {
   Error = "",
   Warning = "",
   Information = "",
   Question = "",
   Hint = "",
 },
 misc = {
   Robot = "ﮧ",
   Plug = " ",
   Squirrel = "",
   Tag = "",
   Watch = "",
 },
}

return icons



--[[ M.cmp_kind = {
  Class = " ",
  Color = " ",
  Constant = "",
  Constructor = " ",
  Default = " ",
  Enum = "練",
  EnumMember = " ",
  Event = " ",
  Field = "ﰠ ",
  File = " ",
  Folder = " ",
  Function = " ",
  Interface = " ",
  Keyword = " ",
  Method = "ƒ ",
  Module = " ",
  Operator = " ",
  Property = " ",
  Reference = "",
  Snippet = " ", -- " "," "
  Struct = "פּ ",
  Text = " ",
  TypeParameter = "  ",
  Unit = "塞",
  Value = " ",
  Variable = " ",
}

M.icons = {
  error = " ",
  warn = " ",
  info = "",
  hint = " ",
  code_action = "",
  test = "",
  docs = "",
  clock = " ",
  calendar = " ",
  buffer = " ",
  settings = " ",
  ls_inactive = "轢",
  ls_active = "歷",
  question = "",
  screen = "冷",
  dart = " ",
  config = " ",
  git = " ",
  magic = " ",
  exit = " ",
  repo = "",
  term = " ",
}

M.nvim_tree_icons = {
  default = "",
  symlink = "",
  git = {
    unstaged = "",
    staged = "",
    unmerged = "",
    renamed = "➜",
    untracked = "",
    deleted = "",
    ignored = "◌",
  },
  folder = {
    arrow_closed = "",
    arrow_open = "",
    default = "",
    open = "",
    empty = "",
    empty_open = "",
    symlink = "",
    symlink_open = "",
  },
}

M.symbols_outline = {
  File = "",
  Module = "",
  Namespace = "",
  Package = "",
  Class = "",
  Method = "ƒ",
  Property = "",
  Field = "",
  Constructor = "",
  Enum = "練",
  Interface = "ﰮ",
  Function = "",
  Variable = "",
  Constant = "",
  String = "𝓐",
  Number = "#",
  Boolean = "⊨",
  Array = "",
  Object = "⦿",
  Key = "",
  Null = "NULL",
  EnumMember = "",
  Struct = "פּ",
  Event = "",
  Operator = "",
  TypeParameter = "𝙏",
}

M.todo_comments = {
  FIX = "律",
  TODO = " ",
  HACK = " ",
  WARN = "裂",
  PERF = "龍",
  NOTE = " ",
  ERROR = " ",
  REFS = "",
}


M.file_icons = {
  Brown = { "" },
  Aqua = { "" },
  LightBlue = { "", "" },
  Blue = { "", "", "", "", "", "", "", "", "", "", "", "", "" },
  DarkBlue = { "", "" },
  Purple = { "", "", "", "", "" },
  Red = { "", "", "", "", "", "" },
  Beige = { "", "", "" },
  Yellow = { "", "", "λ", "", "" },
  Orange = { "", "" },
  DarkOrange = { "", "", "", "", "" },
  Pink = { "", "" },
  Salmon = { "" },
  Green = { "", "", "", "", "", "" },
  LightGreen = { "", "", "", "﵂" },
  White = { "", "", "", "", "", "" },
} ]]
