local settings_status, settings = pcall(require, "control_center")
if not settings_status then
  vim.notify("[settings] failed to load within (rando_scheme.lua)", vim.log.levels.WARN)
  return
end

local rando_opts = settings.theme_plugins.rando_scheme
local key = settings.plugins_keymaps

local rando_scheme = {}

if rando_opts.enable then
  rando_scheme = {
    "Gl00ria/rando_scheme",
    dependencies = { "stevearc/dressing.nvim" },
    opts = {
      keymap = rando_opts.keymap,
      random_startup = rando_opts.random_startup,
      startup_schemes = { -- used for startup schemes & in case the user selected 'random_all' from the menu
        -- fav
        "nord",
        "poimandres",
        "moonlight",
        "nightfox",
        "terafox",
        "onedark",
        "calvera",
        "gruvbox",
        "gruvbox-material",
        "gruvbox-baby",
        "tokyonight",
        "tokyonight-moon",
        "substrata",
        "onedark_vivid",
        "duskfox",
        "nightly",
        "doom-one",
        "neon",
        -- end of fav

        "cyberdream",
        "min-theme",
        "vn-night",
        "OceanicNext",
        "nvcode",
        "oh-lucy ",
        "tokyonight-night",
        "tokyonight-storm",
        "tokyogogh",
        "tokyogogh-night",
        "tokyogogh-storm",
        "catppuccin",
        "catppuccin-frappe",
        "catppuccin-macchiato",
        "catppuccin-mocha",
        "everblush",
        "palenightfall",
        "nordfox",
        "onedark_dark",
        "oxocarbon",
        -- "melange",
        -- "citruszest",
        -- "mellow",
        -- "adwaita",
        -- "monokai-nightasty",
        -- "monokai-pro",
        -- "monokai-pro-classic",
        -- "monokai-pro-default",
        -- "monokai-pro-machine",
        -- "monokai-pro-octagon",
        -- "monokai-pro-ristretto",
        -- "monokai-pro-spectrum",
      },
      night_schemes = {
        -- fav
        "poimandres",
        "nord",
        "nightfox",
        "terafox",
        "onedark",
        "calvera",
        "gruvbox",
        "gruvbox-material",
        "gruvbox-baby",
        "tokyonight",
        "tokyonight-moon",
        "substrata",
        "onedark_vivid",
        "duskfox",
        "nightly",
        "doom-one",
        "neon",
        -- end of fav

        "cyberdream",
        "min-theme",
        "nvcode",
        "tokyonight-night",
        "tokyonight-storm",
        "tokyogogh",
        "tokyogogh-night",
        "tokyogogh-storm",
        "oh-lucy-evening",
        "catppuccin",
        "moonlight",
        "catppuccin-frappe",
        "catppuccin-macchiato",
        "catppuccin-mocha",
        "palenightfall",
        "nordfox",
        "carbonfox",
        "onedark_dark",
        "oxocarbon",
        -- "melange",
        -- "adwaita",
        -- "citruszest",
        -- "mellow",
      },
      day_schemes = {
        -- fav
        "nord",
        "poimandres",
        "onedark",
        "gruvbox-material",
        "substrata",
        "onedark_vivid",
        -- end of fav

        "cyberdream",
        "everblush",
        "vn-night",
        "OceanicNext",
        "nvcode",
        "oh-lucy ",
        "tokyonight-day",
        "tokyogogh",
        "catppuccin",
        "catppuccin-latte",
        "moonlight",
        "palenightfall",
        "nordfox",
        "dawnfox",
        "dayfox",
        "onelight",
        -- "melange",
        -- "monokai-nightasty",
        -- "monokai-pro",
        -- "monokai-pro-classic",
        -- "monokai-pro-default",
        -- "monokai-pro-machine",
        -- "monokai-pro-octagon",
        -- "monokai-pro-ristretto",
        -- "monokai-pro-spectrum",
      },
    },
  }
end
return rando_scheme
